### ISSUE TITLE
Fixes in the second deliverable documentation

### ISSUE THREAD

**Issue by robertops18** [Arquisoft/Inci_i1a#1]
There are some things we have to change of the document:

- Rationale section in InciManagement
- Constraints in the point 9 (Views)
- Include InciManagement and InciDashboard in the context view
- Include runtime quality attributes for InciDashboard

**Comment by pedrytus** [comment]
Directly related to the [final documentation deliverable issue](https://github.com/Arquisoft/Inci_i1a/issues/5).
