### ISSUE TITLE
Documentation - Final Deliverable

### ISSUE THREAD

**Issue by rimorD** [Arquisoft/Inci_i1a#5]

**Comment by rimorD** [comment]
- Added 3 new quality attributes
- Added 8 new quality scenarios
- Updated Table 7. Overview with the new attributes and all the constraints
- Rationale of all submodules have been updated
- Point 9 updated with the constraints

(Pedro, Jorge, Manuel and David):
- Create a new scenario for each constraint
- Constraints list updated
- Optional modifications correctly indicated in the document
- Point 9 updated with new constraints
- 9.2 Loader updated

(Pablo):
- Diagrams have been updated

What's left:
- Divide responsabilities of InciManager into more components
- Make sure names of methods/interfaces are the same in the documentation and in the implementation

**Comment by pedrytus** [comment]
On _May, 8th_ we have met in a general way to finish the documentation in its entirety and thus put an end to that part of the work.

Done.
