### ISSUE TITLE
Extend repository's readme

### ISSUE THREAD

**Issue by rimorD** [Arquisoft/Inci_i1a#7]
A description of the application and its submodules should be written

**Comment by rimorD** [comment]
The readme of the repository has been updated with:
- A brief description of the system and its submodules
- A bit of extra information about the technologies used by the submodules
- The names, uos and the link to the github profile of each team member

**Comment by pedrytus** [comment]
I'm going to include a diagram of the whole project, explaining the interactions between the different parts (technologies) and users.

Working on it.

**Comment by pedrytus** [comment]
I think we can close this issue, in principle the _README_ seems to be acceptable and the criteria that had been defined to be complete are met.
